### PR TITLE
0.1.0

### PR DESCRIPTION
**Pull request by arekkas**
@inyono I upgraded some dependencies, most notably `eslint-plugin-react` which deprecated a few rules:

```
The react/no-comment-textnodes rule is deprecated. Please use the react/jsx-no-comment-textnodes rule instead.
The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.
```

I think those are from the ory eslint dependency. Could you maybe update those?

## todo

* [x] core: have a better createEmptyState #322 
* [x] plugins/spoiler, reducer/editable: remove defaultPlugin #265
* [x] onChange is broken

### CODE REVIEW

**Comment by inyono** [comment]
Yep, see https://github.com/ory-am/eslint-config-ory-am-react/issues/3.

**Comment by inyono** [comment]
Sorry, thought this was an issue xD

**Comment by arekkas** [comment]
Still requires inline elements, we probably need to dupe `col-xs-*` for `.inline` and add `width`

**Comment by arekkas** [comment]
@arekkas please write reg test for c05009f

**Pull request merged**
