### PR TITLE
0.0.0-sprint4

### PR DESCRIPTION
**Pull request by arekkas**
Regarding the following idea
Idea: Add keypad/arrow key movement behavour for selection as well (eg: shift + arrow key).
Problem: Might be broken on mobile

Comment
The shiftkey property in React is handled through instances of SyntheticEvent that homoginises events across different browsers. See for instance the event: onKeyPress  That should work on mobile. If not there is also nativeEvent  See https://facebook.github.io/react/docs/events.html

The fourth sprint is focusing on improving the cross-section editing experience.

sprint4

### CODE REVIEW

**Comment by arekkas** [comment]
## Inter-Section Selection
A little snippet for messing with the user selection (and enabling cross-contenteditable selection): 

```js
var disabled = [];

document.onmousemove = function (e) {
    var e = e || /* IE */ window.event;
    if (e.buttons > 0) {
        if ((e.target.contentEditable === true || e.target.contentEditable === 'true') 
             && disabled.indexOf(e.target) === -1 ) {
            if (disabled.length === 0) {
                e.target.addEventListener('mouseout', disableContentEditable, false);
            } else {
                disableContentEditable(e);
            }
            disabled.push(e.target);
            console.log('Added target ', e.target);
        }
    }
};

document.addEventListener('mousedown', restoreContentEditables);
document.addEventListener('keydown', restoreContentEditables);
    
function restoreContentEditables () {
    for(var i = 0; i < disabled.length; i++) {
        disabled[i].contentEditable = true;
        disabled[i].removeEventListener('mouseout', disableContentEditable, false);;
    }
    disabled = [];
};

function disableContentEditable (e) {
    var e = e || /* IE */ window.event;
    console.log('IS BEING DISABLED', e.target);
    e.target.contentEditable = false;
}
```

http://jsfiddle.net/aeneas/h7jzumw0/3/

Idea: Why not make "editable area" a contenteditable when selecting cross section and handle copy / paste / replace etc events as such?

Idea: Add keypad/arrow key movement behavour for selection as well (eg: shift + arrow key).

*Problem: Might be broken on mobile*

## Snippets

Capture user selection on selection "event":

```js
document.onmousemove = function (e) {
    var e = e || /* IE */ window.event;
    if (e.buttons > 0) {
        console.log(rangy.getSelection());
    }
};
```

*Problem: Might be broken on mobile*

**Comment by arekkas** [comment]
A more advanced use case using nested contenteditables for block level elements: http://jsfiddle.net/aeneas/h7jzumw0/5/

Works okay-ish. We have to see how we can map these changes onto the content model and if the editor is able to deal with this sort of trickery.

**Comment by arekkas** [comment]
## Content Model

A content model is indeed required. We need to have on item per "row", like so:

```json
        {
            "plugin": "text",
            "data": {
                "inner": "Once upon a midnight dreary, while I pondered, weak and weary,Over many a quaint and curious volume of forgotten lore--While I nodded, nearly napping, suddenly there came a tapping,As of some one gently rapping, rapping at my chamber door.\"'Tis some visiter,\" I muttered, \"tapping at my chamber door--Only this and nothing more.\""
            },
            "options": {
                "tag": "p"
            }
        }
```

This should result in:

```html
<p>Once upon a midnight dreary, while I pondered, weak and weary,Over many a quaint and curious volume of forgotten lore--While I nodded, nearly napping, suddenly there came a tapping,As of some one gently rapping, rapping at my chamber door."'Tis some visiter," I muttered, "tapping at my chamber door--Only this and nothing more.
</p>
```

**Comment by arekkas** [comment]
## Plugin capabilities

Plugins should  
* define if a settings modal/dialog is required
* have a versioned content model and provide upgrade paths between the versions
* Have a simple way of embedding an editable area (nesting)

Plugins should not  
* be convertable to other plugins (convert plugin youtube section to text section)

## Nesting areas

Finding a good content model for nesting areas is not an easy task.

### How plugins take control of their container elements

```html
<div class="spoiler">
   <div class="spoiler-button">click to show</div>
   <div class="spoiler-body" style="visible: false">foobar content</div>
</div>
```

In this case, we need the `spoiler-button` element to toggle the `spoiler-body` visibility.

### Area nesting must be possible

```html
<div contenteditable="true">
   <h2>Heading</h2>
   <p>1. paragraph</p>
   <p>2. paragraph</p>
</div>
<div class="spoiler">
   <div class="spoiler-button">click to show</div>
   <div class="spoiler-body" style="visible: false">
      <div contenteditable="true">
         <h2>Heading</h2>
         <p>1. paragraph</p>
         <p>2. paragraph</p>
      </div>
   </div>
</div>
```

### We have to consider the nesting depth

```
|-------|-----------|
| foo   | bar       |
| baz   | |---|---| |
| bez   | | a | b | |
|       | |---|---| |
|-------|-----------|
```

### Don't force a grid system (e.g. bootstrap)

Having multicolumn layouts is a key aspect of this editor. We should not force a grid system but rather make it possible for the developer to choose one of his own:

```html
<div class="row">
   <div class="col-xs-6 area">
      <div contenteditable="true">
         <h2>Heading</h2>
         <p>1. paragraph</p>
         <p>2. paragraph</p>
      </div>
   </div>
   <div class="col-xs-6 area">
      <div contenteditable="true">
         <h2>Heading</h2>
         <p>1. paragraph</p>
         <p>2. paragraph</p>
      </div>
   </div>
</div>
```

A good option for this would be to make as much code from the layout plugin reusable as possible. In this case, each developer could write his own code.

## Joinable sections

```json
{
    "uuid": "5bc68c8e-7948-4b62-858a-ac1c821266e9",
    "sections": [
        {
            "plugin": "text",
            "data": {
                "inner": "Once upon a midnight dreary, while I pondered, weak and weary,Over many a quaint and curious volume of forgotten lore--While I nodded, nearly napping, suddenly there came a tapping,As of some one gently rapping, rapping at my chamber door.\"'Tis some visiter,\" I muttered, \"tapping at my chamber door--Only this and nothing more.\""
            },
            "options": {
                "tag": "p"
            }
        },
        {
            "plugin": "text",
            "data": {
                "inner": "And the Raven, never flitting, still is sitting, still is sittingOn the pallid bust of Pallas just above my chamber door;And his eyes have all the seeming of a demon's that is dreamingAnd the lamp-light o'er him streaming throws his shadows on the floor;And my soul from out that shadow that lies floating on the floorShall be lifted--nevermore!"
            },
            "options": {
                "tag": "p"
            }
        }
    ]
}
```

Should result in:

```html
<div class="area">
   <div contenteditable="true">
      <p>Once upon a midnight dreary, while I pondered, weak and weary,Over many a quaint and curious volume of forgotten lore--While I nodded, nearly napping, suddenly there came a tapping,As of some one gently rapping, rapping at my chamber door.\"'Tis some visiter,\" I muttered, \"tapping at my chamber door--Only this and nothing more.\"</p>
      <p>And the Raven, never flitting, still is sitting, still is sittingOn the pallid bust of Pallas just above my chamber door;And his eyes have all the seeming of a demon's that is dreamingAnd the lamp-light o'er him streaming throws his shadows on the floor;And my soul from out that shadow that lies floating on the floorShall be lifted--nevermore!</p>
   </div>
</div>
```

Whilst


```json
{
    "uuid": "5bc68c8e-7948-4b62-858a-ac1c821266e9",
    "sections": [
        {
            "plugin": "text",
            "data": {
                "inner": "Once upon a midnight dreary, while I pondered, weak and weary,Over many a quaint and curious volume of forgotten lore--While I nodded, nearly napping, suddenly there came a tapping,As of some one gently rapping, rapping at my chamber door.\"'Tis some visiter,\" I muttered, \"tapping at my chamber door--Only this and nothing more.\""
            },
            "options": {
                "tag": "p"
            }
        },
        {
            "plugin": "foobar",
        }
        {
            "plugin": "text",
            "data": {
                "inner": "And the Raven, never flitting, still is sitting, still is sittingOn the pallid bust of Pallas just above my chamber door;And his eyes have all the seeming of a demon's that is dreamingAnd the lamp-light o'er him streaming throws his shadows on the floor;And my soul from out that shadow that lies floating on the floorShall be lifted--nevermore!"
            },
            "options": {
                "tag": "p"
            }
        }
    ]
}
```

Should result in:

```html
<div class="area">
   <div contenteditable="true">
      <p>Once upon a midnight dreary, while I pondered, weak and weary,Over many a quaint and curious volume of forgotten lore--While I nodded, nearly napping, suddenly there came a tapping,As of some one gently rapping, rapping at my chamber door.\"'Tis some visiter,\" I muttered, \"tapping at my chamber door--Only this and nothing more.\"</p>
   </div>
   <div class="foobar">placeholder</div>
   <div  contenteditable="true">
      <p>And the Raven, never flitting, still is sitting, still is sittingOn the pallid bust of Pallas just above my chamber door;And his eyes have all the seeming of a demon's that is dreamingAnd the lamp-light o'er him streaming throws his shadows on the floor;And my soul from out that shadow that lies floating on the floorShall be lifted--nevermore!</p>
   </div>
</div>
```

**Comment by arekkas** [comment]
## Plugins

Should attach to the editor instance for listening on changes:

```js
editor.sections.addEventListener('create|delete|focus|blur', () => {})
```

Or even better by using flux stores/actions.

We should get rid of `createSection` and rely on defaults instead

**Comment by arekkas** [comment]
## A thought on states

dsc_0722

**Comment by arekkas** [comment]
Results from yesterday's pair programming:

- Some sort of JSON store is required for plugins to work. This could be either as an HTMLElement Attribute or in a SaaS environment
- To save the JSON representation via SaaS, we require some sort of identification to prevent malicious use (e.g. reading private API keys, modifying content without proper authorization). This could be done via hooking into the CMS' POST routine, via OAuth or via Tokens (Auth OR/AND UUID)

@inyono feel free to comment if I forgot something

**Comment by inyono** [comment]
## Hooks in popular CMSs

* [Usage of CMSs](http://w3techs.com/technologies/overview/content_management/all)

### Wordpress

* [Plugin Handbook](https://developer.wordpress.org/plugins/)
* [Plugin API/Action Reference](https://codex.wordpress.org/Plugin_API/Action_Reference), e.g.: `save post`

  > Runs whenever a post or page is created or updated. Runs after the data is saved to the database.

### Joomla

* [Plugin](https://docs.joomla.org/Plugin)
* [Plugin/Events](https://docs.joomla.org/Plugin/Events), e.g. `onContentAfterSave`

  > This is an event that is called after the content is saved into the database.

### Drupal

* [Module developer's guide](https://www.drupal.org/developing/modules)
* [Module system (Drupal 7 hooks)](https://api.drupal.org/api/drupal/includes%21module.inc/group/hooks/7) e.g. `hook_entity_update`

  > Act on entities when updated.

### TYPO3

* [Hooks](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Hooks/Index.html)
* [Extending classes (XCLASSes)](https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/Xclasses/Index.html)

**Comment by arekkas** [comment]
## State report

After plowing through the internet I think I finally found a good editor to use as a basis for the text editing part: [ProseMirror](http://prosemirror.net). It is initiated by the guy who wrote CodeMirror (which is used at [Serlo](https://de.serlo.org) right now) and is backed by 420 people and ~50k€ [crowdfunding campaign](https://www.indiegogo.com/projects/prosemirror#/), overshooting the aim of 35k€.

It is written in *es6*, looks like it has a very solid architecture which is going to be easy to extend and uses a *content model*, which basically no open source contenteditable solution has done yet.

The main focus right now is to figure out what and how to wrap these contenteditables and how to make cross section changes possible. The golden aim can be sumed up as: **I want to move around elements and text freely, dropping them anywhere in the content while maintaining a sane representation of the content.** (subject to change)

**Pull request closed without merging**
